gpu_id: '2'
log_wandb: false
logging:
  level: DEBUG

embedding_size: 256      
step: 1                        
loss_type: 'CE'              


# Save Directory Settings
checkpoint_dir: 'SavedData'
save_dataloaders: False
dataloaders_save_path: '' 
save_dataset: True         
dataset: gowalla
dataset_save_path: 'SavedData/gowalla.pth'  
seed: 42  
train_neg_sample_args:  null


#Dataset Settings
USER_ID_FIELD: user_id
ITEM_ID_FIELD: venue_id
TIME_FIELD: timestamp
LABEL_FIELD: label

load_col:
    inter: [user_id, venue_id,timestamp]
    item: [venue_id,latitude, longitude]

LIST_SUFFIX: "_list"
MAX_ITEM_LIST_LENGTH: 32
ITEM_LIST_LENGTH_FIELD: venue_seq_len



Use_CustomDataset: True 
Use_CustomSampler: False
repeatable: True  
NEG_PREFIX: "neg_"

model: SRGNN

# training settings
epochs: 40
train_batch_size: 4096
learner: adam
learning_rate: 0.001
eval_step: 1
stopping_step: 4
single_spec: True


train_neg_sample_args: ~ #CE

eval_args:
  order: TO 
  spilt: 
    RS: [0.7,0.1,0.2]
  gourp_by: user_id
  max_seq_len: 32 
  mode:
    val: full
    test: full



# evalution settings
metrics: ['Recall', 'MRR','NDCG','ItemCoverage','AveragePopularity','TailPercentage']
valid_metric: NDCG@10
eval_batch_size: 4096
weight_decay: 0.01
topk: [1,5,10,20]
tail_ratio: 0.15





